services:
  db:
    image: mysql:8.1
    ports:
      - 3307:3307
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=courses
  backend:
    build: backend
    ports:
      - 3001:3001
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=courses
    depends_on:
      - db
  frontend:
    build: frontend
    ports:
      - 3000:3000
    environment:
      - API_BASE_URL=http://backend:3001
    depends_on:
      - backend

